version: '2'
services:
    avaliacao360zanco-postgresql:
        container_name: avaliacao360zanco-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/avaliacao360Zanco/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=avaliacao360Zanco
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
