@startuml

class User {
    - id : Long
    - login : String
    - password : String
    - firstName : String
    - lastName : String
    - email : String
    - activated : boolean
    - langKey : String
    - activationKey : String
    - resetKey : String
    - resetDate : ZonedDateTime
}

class Equipe {
    - id : Long 
    - nome : String 
    - descricao : String
    - lider : User
}

class AvaliacaoModelo{
    - id : Long
    - nome : String
    - descricao : String
}

class Avaliacao{
    - id : Long 
    - nome : String
    - descricao : String
}

class PerguntaModelo{
    - id : Long
    - assunto : String
    - texto : String
}

class Pergunta {
    - id : Long
    - assunto : String
    - texto : String
}

class Resposta{
    - id : Long
    - comentario : String
    - nota : int
}

Equipe "0..*" o--> "1" User : lider
Equipe "0..*" o--> "0..*" User : membros
Equipe "1" o--> "0..*" AvaliacaoModelo
AvaliacaoModelo "1" o--> "0..*" PerguntaModelo
User "1" o--> "0..*" Avaliacao : "avaliado"
User "1" o--> "0..*" Avaliacao : "avaliador"
note left on link
Null após avaliador
fazer avaliação
end note
Avaliacao "1" o--> "0..*" Pergunta
Pergunta "1" o--> "0..*" Resposta


@enduml